WebApplication8/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WishList.Models
{
    public class Item
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Description { get; set; }
    }
}

WebApplication8/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WishList.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View("Index");
        }
        public IActionResult Error()
        {
            return View("Error");
        }
    }
}

WebApplication8/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WishList.Data;

namespace WishList.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var model = _context.Items.ToList();
            return View("Index", model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(Models.Item item)
        {
            _context.Items.Add(item);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public IActionResult Delete(int id)
        {
            var item = _context.Items.FirstOrDefault(e => e.Id == id);
            _context.Items.Remove(item);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication8/Views/Home/Index.cshtml
<h1>Welcome to Wishlist, User! </h1>
<a asp-action="Index" asp-controller="Item">View wishlist</a>

WebApplication8/Views/Item/Create.cshtml
@model WishList.Models.Item;
<h3>Add item to wishlist  </h3>
<form asp-action="create">
    <input asp-for="Description" />
    <span asp-validation-for="Description"></span>
    <button type="submit">Add Item </button>
</form>

WebApplication8/Views/Item/Index.cshtml
@model List<WishList.Models.Item>
<h1>Wishlist</h1>
<a asp-action="create">Add item</a>
<ul>
    @foreach (var item in Model)
    {
        <li>@item.Description <a asp-action="delete" asp-route-id="@item.Id">delete</a></li>
    }
</ul>

WebApplication8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>WishList</title>

        <!-- Handles styling the page to be more aesthetically pleasing -->
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css" />
    </head>

    <body>
        <!-- Where view content will be rendered -->
        <div class="col-sm-12">
            @RenderBody()
        </div>

        <!-- Needed for client side validation, dialogs, etc -->
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.0.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    </body>
</html>